{
 "title": "New dashboard2",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_uptime_seconds" }
   ]
  },
  {
   "title": "HTTP Request Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{uri!=\"/actuator/prometheus\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 10, "y": 0 },
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "{{application}}" }
   ]
  },
  {
   "title": "HTTP Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri!=\"/actuator/prometheus\"}",
     "legendFormat": "{{method}} {{application}}"
    }
   ]
  },
  {
   "title": "HTTP Response Time (Median)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds{quantile=\"0.5\"}",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  }
 ]
}